### ISSUE TITLE
For win10 python 3.5 error

### ISSUE THREAD

**Issue by tuteming** [Heumi/Fast_Multi_Style_Transfer-tf#4]
my test.bat is 
python main.py -f 0 -gn 0 -p MST -tsd images/test/ -scw 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
but have the following error
-----------------------------------------------------
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "main.py", line 52, in main
    model = mst.mst(args, sess)
  File "f:\test_tensorflow\Multi_style_transfer\src\multi_style_transfer.py", line 13, in __init__
    op.__init__(self, args, sess)
  File "f:\test_tensorflow\Multi_style_transfer\src\op.py", line 46, in __init__
    self.build_model()
  File "f:\test_tensorflow\Multi_style_transfer\src\multi_style_transfer.py", line 49, in build_model
    MST_output    = self.mst_net(self.content_input, style_control=self.style_control)
  File "f:\test_tensorflow\Multi_style_transfer\src\multi_style_transfer.py", line 19, in mst_net
    x = conv_layer(x, 32, 9, 1, style_control=style_control, name='conv1')
  File "f:\test_tensorflow\Multi_style_transfer\src\layers.py", line 13, in conv_layer
    net = tf.pad(net, [[0, 0], [p, p], [p, p], [0, 0]], "REFLECT")
  File "C:\Users\duo\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1659, in pad
    name=name)
  File "C:\Users\duo\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1641, in _mirror_pad
    mode=mode, name=name)
  File "C:\Users\duo\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 589, in apply_op
    param_name=input_name)
  File "C:\Users\duo\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'paddings' has DataType float32 not in list of allowed values: int32, int64
------------------------------------------------
please tell me how to correct this error?
thanks

**Comment by wunengguang** [comment]
hello sir !
beaucse our goverment  bind net about  cocodataset and dropbox . So i hope you can put all file on github. thank you sir

**Comment by suzdi** [comment]
I'm in same trouble... Did you solve it?
