### ISSUE TITLE
ValueError: No variables to optimize.

### ISSUE THREAD

**Issue by JefferyLJF1129** [Heumi/Fast_Multi_Style_Transfer-tf#7]
when i run the training code, it reports:

```
E:\计算机视觉大作业\MultiStyle\Fast_Multi_Style_Transfer-tensorflow-master\Fast_Multi_Style_Transfer-tensorflow-master>python main.py -f 1 -gn 0 -p MST -n 10 -b 16 -tsd images/test -sti images/style_crop/0_udnie.jpg -ctd /mnt/cloud/Data/COCO/train2014 -scw 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
2019-04-28 22:05:09.742580: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From C:\Users\jiefeng\Documents\SOFTWARE\Python\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
style_idx : [0]
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main()
  File "main.py", line 50, in main
    model = mst.mst(args, sess)
  File "E:\计算机视觉大作业\MultiStyle\Fast_Multi_Style_Transfer-tensorflow-master\Fast_Multi_Style_Transfer-tensorflow-master\src\multi_style_transfer.py", line 12, in __init__
    op.__init__(self, args, sess)
  File "E:\计算机视觉大作业\MultiStyle\Fast_Multi_Style_Transfer-tensorflow-master\Fast_Multi_Style_Transfer-tensorflow-master\src\op.py", line 45, in __init__
    self.build_model()
  File "E:\计算机视觉大作业\MultiStyle\Fast_Multi_Style_Transfer-tensorflow-master\Fast_Multi_Style_Transfer-tensorflow-master\src\multi_style_transfer.py", line 69, in build_model
    train_opt = tf.train.AdamOptimizer(self.learning_rate, self.momentum).minimize(loss, var_list=vars)
  File "C:\Users\jiefeng\Documents\SOFTWARE\Python\Anaconda\lib\site-packages\tensorflow\python\training\optimizer.py", line 403, in minimize
    grad_loss=grad_loss)
  File "C:\Users\jiefeng\Documents\SOFTWARE\Python\Anaconda\lib\site-packages\tensorflow\python\training\optimizer.py", line 506, in compute_gradients
    raise ValueError("No variables to optimize.")
ValueError: No variables to optimize.
```

**Comment by JefferyLJF1129** [comment]
can somebody save me QAQ???
